language: cpp

addons:
  apt:
    packages:
      - g++-multilib
      - lib32z1-dev

env:
  global:
    - SOURCEMOD_VERSION=1.10-dev

jobs:
  include:
    - name: "linux build"
      compiler: clang
      python: 3.8
      os: linux

install:
  - git clone https://github.com/alliedmodders/sourcemod.git -b $SOURCEMOD_VERSION --depth 1 -j8 --recurse-submodules --shallow-submodules $TRAVIS_BUILD_DIR/../sourcemod
  - git clone https://github.com/alliedmodders/ambuild.git --depth 1 $TRAVIS_BUILD_DIR/../ambuild
  - pip install --upgrade pip
  - pip install $TRAVIS_BUILD_DIR/../ambuild

script:
  - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
  - python3 ../configure.py --enable-optimize
  - ambuild
 
