git:
  depth: 3

language: cpp
os: linux

env:
  global:
    - SOURCEMOD_VERSION=1.10-dev

jobs:
  include:
    - name: "Linux clang"
      compiler: clang
      python: 3.8
      os: linux
      addons:
        apt:
          packages:
            - g++-multilib
            - lib32z1-dev

install:
  - pip install --upgrade pip
  - pip install setuptools
  - git clone https://github.com/alliedmodders/sourcemod.git -b $SOURCEMOD_VERSION --depth 1 -j8 --recurse-submodules --shallow-submodules $TRAVIS_BUILD_DIR/../sourcemod
  - bash ./travis/checkout-deps

before_script:
  - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build

script:
  - python ../configure.py --enable-optimize
  - ambuild
 
