language: cpp

addons:
  apt:
    packages:
      - g++-multilib
      - lib32z1-dev

env:
  global:
    - SOURCEMOD_VERSION=1.10-dev

jobs:
  include:
    - name: "linux build"
      compiler: clang
      python: 3.8
      os: linux

install:
  - pip install --upgrade pip
  - pip install setuptools
  - git clone https://github.com/alliedmodders/sourcemod.git -b $SOURCEMOD_VERSION --depth 1 -j8 --recurse-submodules --shallow-submodules $TRAVIS_BUILD_DIR/../sourcemod
  - git clone https://github.com/alliedmodders/ambuild.git --depth 1 $TRAVIS_BUILD_DIR/../ambuild
  - git clone https://github.com/alliedmodders/metamod-source.git -b 1.10-dev --depth 1 $TRAVIS_BUILD_DIR/../mmsource-1.10
  - git clone https://github.com/alliedmodders/hl2sdk.git -b css --depth 1 $TRAVIS_BUILD_DIR/../hl2sdk-css
  - git clone https://github.com/alliedmodders/hl2sdk.git -b csgo --depth 1 $TRAVIS_BUILD_DIR/../hl2sdk-csgo
  - pip install $TRAVIS_BUILD_DIR/../ambuild
  - git clone 

before_script:
  - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
  - python ../configure.py --enable-optimize --sdks=csgo,css

script:
  - ambuild
 
