language: cpp

addons:
  apt:
    packages:
      - g++-multilib
      - lib32z1-dev

env:
  global:
    - SOURCEMOD_VERSION=1.10-dev

jobs:
  include:
    - name: "linux build"
      compiler: clang
      python: 3.8
      os: linux

install:
  - pip install --upgrade pip
  - pip install setuptools
  - git clone https://github.com/alliedmodders/sourcemod.git -b $SOURCEMOD_VERSION --depth 1 -j8 --recurse-submodules --shallow-submodules $TRAVIS_BUILD_DIR/../sourcemod
  - cp $TRAVIS_BUILD_DIR/../sourcemod/tools/checkout-deps.sh $TRAVIS_BUILD_DIR/ 
  - bash $TRAVIS_BUILD_DIR/checkout-deps.sh

before_script:
  - mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
  - python ../configure.py --enable-optimize

script:
  - ambuild
 
